name: Unlighthouse Report

concurrency:
  group: unlighthouse

on:
  push:
    branches:
      - 'release'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

permissions:
  contents: write
  actions: write
  repository-projects: read

jobs:
  unlighthouse:
    name: Generate Unlighthouse Report

    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Setup node_modules cache'
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: node-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Run Unlighthouse CI
        run: |
          npm run unlighthouse-ci

      - name: Deploy Unlighthouse report to GitHub Pages
        if: success() || failure()
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: .unlighthouse
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
